rep_gestion_homepage:
    pattern:  /
    defaults: { _controller: RepGestionBundle:Start:index }
    
rep_gestion_login:
    pattern:  /login
    defaults: { _controller: RepGestionBundle:Login:index }
    
rep_gestion_accueil:
    pattern:  /accueil
    defaults: { _controller: RepGestionBundle:Accueil:index }


# Route pour admin

add_admin:
    pattern:  /admin/ajouter
    defaults: { _controller: RepGestionBundle:Admin:ajouter }

list_one_admin:
    pattern:  /admin/list/{codeSecret}
    defaults: { _controller: RepGestionBundle:Admin:list }
    requirements:
        id: \d+
        
list_all_admin:
    pattern:  /admin/listAll/
    defaults: { _controller: RepGestionBundle:Admin:listAll }
    
update_admin:
    pattern:  /admin/modifier/{id}
    defaults: { _controller: RepGestionBundle:Admin:update }
    requirements:
        id: \d+
        
delete_admin:
    pattern:  /admin/supprimer/{id}
    defaults: { _controller: RepGestionBundle:Admin:delete }
    requirements:
        id: \d+
        

# Route pour un Personnel


add_personnel:
    pattern:  /personnel/ajouter
    defaults: { _controller: RepGestionBundle:Direction:addPersonnel }
    
save_personnel:
    pattern:  /personnel/save
    defaults: { _controller: RepGestionBundle:Direction:savePersonnel }

list_one_personnel:
    pattern:  /personnel/list/{id}
    defaults: { _controller: RepGestionBundle:Personnel:list }
    requirements:
        id: \d+
        
list_all_personnel:
    pattern:  /personnel/listAll/
    defaults: { _controller: RepGestionBundle:Direction:listAllPersonnel }
    
update_personnel:
    pattern:  /personnel/modifier/{id}
    defaults: { _controller: RepGestionBundle:Direction:updatePersonnel }
    requirements:
        id: \d+
        
delete_personnel:
    pattern:  /personnel/supprimer/{id}
    defaults: { _controller: RepGestionBundle:Personnel:delete }
    requirements:
        id: \d+
        
        

# Route pour une Categorie

add_categorie:
    pattern:  /categorie/ajouter/
    defaults: { _controller: RepGestionBundle:Direction:addCategorie }

list_one_categorie:
    pattern:  /categorie/list/{id}
    defaults: { _controller: RepGestionBundle:Categorie:list }
    requirements:
        id: \d+
        
list_all_categorie:
    pattern:  /categorie/listAll/
    defaults: { _controller: RepGestionBundle:Categorie:listAll }
    
update_categorie:
    pattern:  /categorie/modifier/{id}
    defaults: { _controller: RepGestionBundle:Categorie:update }
    requirements:
        id: \d+
        
delete_categorie:
    pattern:  /categorie/supprimer/{id}
    defaults: { _controller: RepGestionBundle:Categorie:delete }
    requirements:
        id: \d+
        
        
        # Route pour une Compte

add_compte:
    pattern:  /compte/ajouter/
    defaults: { _controller: RepGestionBundle:Direction:addCompte }

list_one_compte:
    pattern:  /compte/list/{id}
    defaults: { _controller: RepGestionBundle:Compte:list }
    requirements:
        id: \d+
        
list_all_compte:
    pattern:  /compte/listAll/
    defaults: { _controller: RepGestionBundle:Direction:listAllCompte }
    
update_compte:
    pattern:  /compte/modifier/{id}
    defaults: { _controller: RepGestionBundle:Direction:updateCompte }
    requirements:
        id: \d+
        
delete_compte:
    pattern:  /compte/supprimer/{id}
    defaults: { _controller: RepGestionBundle:Direction:deleteCompte }
    requirements:
        id: \d+
        
        
        
                # Route pour une Poste

add_poste:
    pattern:  /poste/ajouterAlaDirection/{id}
    defaults: { _controller: RepGestionBundle:Direction:addPoste }
    requirements:
        id: \d+

list_one_poste:
    pattern:  /poste/list/{id}
    defaults: { _controller: RepGestionBundle:Poste:list }
    requirements:
        id: \d+
        
list_all_poste:
    pattern:  /poste/listAll/
    defaults: { _controller: RepGestionBundle:Poste:listAll }
    
update_poste:
    pattern:  /poste/modifier/{id}/{idPoste}
    defaults: { _controller: RepGestionBundle:Direction:updatePoste }
    requirements:
        id: \d+
        idPoste: \d+
        
delete_poste:
    pattern:  /poste/supprimer/{id}
    defaults: { _controller: RepGestionBundle:Poste:delete }
    requirements:
        id: \d+
        
        
        
                
                # Route pour une Direction
                

add_direction:
    pattern:  /direction/ajouter/
    defaults: { _controller: RepGestionBundle:Direction:ajouter }

list_one_direction:
    pattern:  /direction/list/{id}
    defaults: { _controller: RepGestionBundle:Direction:list }
    requirements:
        id: \d+
        
list_all_direction:
    pattern:  /direction/listAll/
    defaults: { _controller: RepGestionBundle:Direction:listAll }
    
list_tree_direction:
    pattern:  /direction/arbre/
    defaults: { _controller: RepGestionBundle:Direction:builTree }
    
list_detail_direction:
    pattern:  /direction/detail/{id}
    defaults: { _controller: RepGestionBundle:Direction:detail }
    requirements:
        id: \d+
    
update_direction:
    pattern:  /direction/modifier/{id}/{idDir}
    defaults: { _controller: RepGestionBundle:Direction:updateBranche }
    requirements:
        id: \d+
        idDir: \d+
        
delete_direction:
    pattern:  /direction/supprimer/{id}
    defaults: { _controller: RepGestionBundle:Direction:delete }
    requirements:
        id: \d+
        
list_sous_direction:
    pattern:  /direction/listSousDirection/{id}
    defaults: { _controller: RepGestionBundle:Direction:listSousDir }
    requirements:
        id: \d+
        
add_branche:
    pattern:  /branche/ajouterAlaDirection/{id}
    defaults: { _controller: RepGestionBundle:Direction:addBranche }
    requirements:
        id: \d+
        
export_data_branche:
    pattern:  /branche/export-Donnees/{id}
    defaults: { _controller: RepGestionBundle:Direction:exportDirectionData }
    requirements:
        id: \d+
        
        
impression_data:
    pattern: //branche/{id}/impression
    defaults: { _controller: RepGestionBundle:Direction:buildExcel }